/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Eduardo
 */
public class Sobre extends javax.swing.JFrame {

    /**
     * Creates new form Sobre
     */
    public Sobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtSobre = new javax.swing.JLabel();
        jbotaoret = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtSobre.setBackground(new java.awt.Color(0, 204, 255));
        jtxtSobre.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jtxtSobre.setText("<html>Olá somos os desevolvedores do sotfware \"Pegasus book\" e queriamos agradecer por utilizar do nosso programa. o intuito de criamos este veio da necessidade de digitalizar nossa bibilioteca pois em plena era digital ainda utilizamos o papel para armazenar dados, \"vinhemos para atualizar o sistema evoluir a maneira de se organizar e armazenar informações\". <br> \t   \t\t\titapipoca 16/11/2017 <br> \t\t\t\tescritor: Luis eduardo  <br> \t\t\t\t\tcorretor: joão francisco  <br> \t\t\t\t\t\t\t\tCEO:Claudevan  <br>    Luis diz sobre o solftware:\"É algo inovador e que veio para ser unico com seu designer impactante e usabilidade simples\".(criador do  designer  do solftware)  <br>  João francisco diz sobre o soltware :\"Solftware que condiz com a realidade atual. Em seu carater inspirador e imponente veio para tornar sua vida mais organizada\".(redator e idealista do solftware)  <br>  Claudevan diz sobre o soltware:\"Um soltware simples mas com intenções grandiosas\" (CEO e programador do software)  <br>      \t\t\t\t”Seja um parâmetro de qualidade. Algumas pessoas não estão acostumadas a um ambiente onde a excelência é esperada.”   <br> </html>");
        jtxtSobre.setToolTipText("");
        jtxtSobre.setOpaque(true);
        jPanel1.add(jtxtSobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 697, 260));

        jbotaoret.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/back_arrow_14447.png"))); // NOI18N
        jbotaoret.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbotaoretMouseClicked(evt);
            }
        });
        jPanel1.add(jbotaoret, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 50));

        jMenu1.setText("Desenvolvedores>>>");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbotaoretMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbotaoretMouseClicked
        Tela_login tela = new Tela_login();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jbotaoretMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
       Desenvolvedores tela = new Desenvolvedores();
       tela.setVisible(true);
       tela.setLocationRelativeTo(null);
       this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sobre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jbotaoret;
    private javax.swing.JLabel jtxtSobre;
    // End of variables declaration//GEN-END:variables
}
